export const data = [
  { name: 'Acrylin', density: 1190 },
  { name: 'Aerogel', density: 1 },
  { name: 'Aerographite', density: 0.2 },
  { name: 'Agba', density: 710 },
  { name: 'Air', density: 1.2 },
  { name: 'Aluminium', density: 2700 },
  { name: 'Antimony', density: 6690 },
  { name: 'Apple seed', density: 32 },
  { name: 'Asbestos', density: 2450 },
  { name: 'Ashes', density: 650 },
  { name: 'Asphalt liquid', density: 65 },
  { name: 'Bamboo', density: 360 },
  { name: 'Barium', density: 3595 },
  { name: 'Beryl', density: 2700 },
  { name: 'Beryllium', density: 1850 },
  { name: 'Biotite', density: 2900 },
  { name: 'Bismuth', density: 9750 },
  { name: 'Bone', density: 1850 },
  { name: 'Brass', density: 8.6 },
  { name: 'Brick hard', density: 2000 },
  { name: 'Butter', density: 860 },
  { name: 'Cadmium', density: 8650 },
  { name: 'Caesium', density: 1870 },
  { name: 'Calcium', density: 1550 },
  { name: 'Cerium', density: 6770 },
  { name: 'Chalk', density: 2450 },
  { name: 'Chromium', density: 7100 },
  { name: 'Cinnabar', density: 8100 },
  { name: 'Clay', density: 2200 },
  { name: 'Cobalt', density: 8900 },
  { name: 'Columbium', density: 8550 },
  { name: 'Concrete', density: 2400 },
  { name: 'Cooking oil', density: 930 },
  { name: 'Copper', density: 8790 },
  { name: 'Cork', density: 240 },
  { name: 'Corundum', density: 4000 },
  { name: 'Cotton', density: 80 },
  { name: 'Diamond', density: 3500 },
  { name: 'Diiodomethane', density: 3325 },
  { name: 'Emery', density: 4000 },
  { name: 'Erbium', density: 9070 },
  { name: 'Flint', density: 2600 },
  { name: 'Fluorite', density: 3200 },
  { name: 'Gallium', density: 5900 },
  { name: 'Germanium', density: 5320 },
  { name: 'Glass wool', density: 25 },
  { name: 'Glass', density: 2210 },
  { name: 'Glycerol', density: 1261 },
  { name: 'Glue', density: 1300 },
  { name: 'Gold', density: 19320 },
  { name: 'Granite', density: 2700 },
  { name: 'Graphite', density: 2500 },
  { name: 'Helium', density: 0.179 },
  { name: 'Hydrogen', density: 0.0898 },
  { name: 'Ice', density: 917 },
  { name: 'Yellow brass', density: 8470 },
  { name: 'Yew', density: 670 },
  { name: 'Indium', density: 7310 },
  { name: 'Iridium', density: 22420 },
  { name: 'Iron', density: 7870 },
  { name: 'Ivory', density: 1800 },
  { name: 'Kaolin', density: 2600 },
  { name: 'Lead Crystal', density: 3100 },
  { name: 'Lead', density: 11340 },
  { name: 'Limestone', density: 2800 },
  { name: 'Liquid hydrogen', density: 70 },
  { name: 'Liquid oxygen', density: 1141 },
  { name: 'Lithium', density: 530 },
  { name: 'Logwood', density: 910 },
  { name: 'Magnesium', density: 1740 },
  { name: 'Manganese', density: 7325 },
  { name: 'Mercury', density: 13546 },
  { name: 'Metallic microlattice', density: 0.9 },
  { name: 'Molybdenum', density: 10220 },
  { name: 'Neptunium', density: 20200 },
  { name: 'Nickel', density: 8900 },
  { name: 'Nylon', density: 1150 },
  { name: 'Nimonic', density: 8100 },
  { name: 'Niobium', density: 8570 },
  { name: 'Oak', density: 720 },
  { name: 'Osmium', density: 22570 },
  { name: 'Paper', density: 700 },
  { name: 'Phosphorus', density: 1820 },
  { name: 'Pine', density: 350 },
  { name: 'Plastics', density: 1175 },
  { name: 'Platinum', density: 21450 },
  { name: 'Plutonium', density: 19840 },
  { name: 'Polonium', density: 9200 },
  { name: 'Potassium', density: 860 },
  { name: 'Promethium', density: 7260 },
  { name: 'Quartz', density: 2650 },
  { name: 'Radium', density: 5000 },
  { name: 'Red brass', density: 8720 },
  { name: 'Redwood', density: 510 },
  { name: 'Rhenium', density: 21020 },
  { name: 'Rhodium', density: 12410 },
  { name: 'Rock salt', density: 2200 },
  { name: 'Rock wool', density: 300 },
  { name: 'Rubidinium', density: 1520 },
  { name: 'Ruthenium', density: 12100 },
  { name: 'Sand dry', density: 1500 },
  { name: 'Sapphire', density: 3980 },
  { name: 'Selenium', density: 4800 },
  { name: 'Silicon', density: 2330 },
  { name: 'Silver', density: 10500 },
  { name: 'Slate', density: 2900 },
  { name: 'Snow', density: 100 },
  { name: 'SoapStone', density: 2900 },
  { name: 'Sodium', density: 980 },
  { name: 'Soy beans', density: 4 },
  { name: 'Steel', density: 7820 },
  { name: 'Styrofoam', density: 75 },
  { name: 'Stone', density: 2600 },
  { name: 'Sugar', density: 1600 },
  { name: 'Tantalum', density: 16600 },
  { name: 'Tetrachloroethene', density: 1622 },
  { name: 'Thorium', density: 11700 },
  { name: 'Tin', density: 7310 },
  { name: 'Titanium', density: 4540 },
  { name: 'Topaz', density: 3500 },
  { name: 'Tungsten hexafluoride', density: 12.4 },
  { name: 'Tungsten', density: 19300 },
  { name: 'Uranium', density: 18800 },
  { name: 'Vanadium', density: 6100 },
  { name: 'Water(salt)', density: 1030 },
  { name: 'Water', density: 1000 },
  { name: 'Wood', density: 700 },
  { name: 'Zebrawood', density: 790 },
  { name: 'Zinc', density: 7120 },
  { name: 'Zirconium', density: 6520 },
];
