export const data = [
  { name: 'Acrylin', density: 1190, url: '@AA' },
  { name: 'Aerogel', density: 1, url: '@AA' },
  { name: 'Aerographite', density: 0.2, url: '@AA' },
  { name: 'Agba', density: 710, url: '@AA' },
  { name: 'Air', density: 1.2, url: '@AA' },
  { name: 'Aluminium', density: 2700, url: '@AA' },
  { name: 'Antimony', density: 6690, url: '@AA' },
  { name: 'Apple seed', density: 32, url: '@AA' },
  { name: 'Asbestos', density: 2450, url: '@AA' },
  { name: 'Ashes', density: 650, url: '@AA' },
  { name: 'Asphalt liquid', density: 65, url: '@AA' },
  { name: 'Bamboo', density: 360, url: '@AA' },
  { name: 'Barium', density: 3595, url: '@AA' },
  { name: 'Beryl', density: 2700, url: '@AA' },
  { name: 'Beryllium', density: 1850, url: '@AA' },
  { name: 'Biotite', density: 2900, url: '@AA' },
  { name: 'Bismuth', density: 9750, url: '@AA' },
  { name: 'Bone', density: 1850, url: '@AA' },
  { name: 'Brass', density: 8.6, url: '@AA' },
  { name: 'Brick hard', density: 2000, url: '@AA' },
  { name: 'Butter', density: 860, url: '@AA' },
  { name: 'Cadmium', density: 8650, url: '@AA' },
  { name: 'Caesium', density: 1870, url: '@AA' },
  { name: 'Calcium', density: 1550, url: '@AA' },
  { name: 'Cerium', density: 6770, url: '@AA' },
  { name: 'Chalk', density: 2450, url: '@AA' },
  { name: 'Chromium', density: 7100, url: '@AA' },
  { name: 'Cinnabar', density: 8100, url: '@AA' },
  { name: 'Clay', density: 2200, url: '@AA' },
  { name: 'Cobalt', density: 8900, url: '@AA' },
  { name: 'Columbium', density: 8550, url: '@AA' },
  { name: 'Concrete', density: 2400, url: '@AA' },
  { name: 'Cooking oil', density: 930, url: '@AA' },
  { name: 'Copper', density: 8790, url: '@AA' },
  { name: 'Cork', density: 240, url: '@AA' },
  { name: 'Corundum', density: 4000, url: '@AA' },
  { name: 'Cotton', density: 80, url: '@AA' },
  { name: 'Diamond', density: 3500, url: '@AA' },
  { name: 'Diiodomethane', density: 3325, url: '@AA' },
  { name: 'Emery', density: 4000, url: '@AA' },
  { name: 'Erbium', density: 9070, url: '@AA' },
  { name: 'Flint', density: 2600, url: '@AA' },
  { name: 'Fluorite', density: 3200, url: '@AA' },
  { name: 'Gallium', density: 5900, url: '@AA' },
  { name: 'Germanium', density: 5320, url: '@AA' },
  { name: 'Glass wool', density: 25, url: '@AA' },
  { name: 'Glass', density: 2210, url: '@AA' },
  { name: 'Glycerol', density: 1261, url: '@AA' },
  { name: 'Glue', density: 1300, url: '@AA' },
  { name: 'Gold', density: 19320, url: '@AA' },
  { name: 'Granite', density: 2700, url: '@AA' },
  { name: 'Graphite', density: 2500, url: '@AA' },
  { name: 'Helium', density: 0.179, url: '@AA' },
  { name: 'Hydrogen', density: 0.0898, url: '@AA' },
  { name: 'Ice', density: 917, url: '@AA' },
  { name: 'Yellow brass', density: 8470, url: '@AA' },
  { name: 'Yew', density: 670, url: '@AA' },
  { name: 'Indium', density: 7310, url: '@AA' },
  { name: 'Iridium', density: 22420, url: '@AA' },
  { name: 'Iron', density: 7870, url: '@AA' },
  { name: 'Ivory', density: 1800, url: '@AA' },
  { name: 'Kaolin', density: 2600, url: '@AA' },
  { name: 'Lead Crystal', density: 3100, url: '@AA' },
  { name: 'Lead', density: 11340, url: '@AA' },
  { name: 'Limestone', density: 2800, url: '@AA' },
  { name: 'Liquid hydrogen', density: 70, url: '@AA' },
  { name: 'Liquid oxygen', density: 1141, url: '@AA' },
  { name: 'Lithium', density: 530, url: '@AA' },
  { name: 'Logwood', density: 910, url: '@AA' },
  { name: 'Magnesium', density: 1740, url: '@AA' },
  { name: 'Manganese', density: 7325, url: '@AA' },
  { name: 'Mercury', density: 13546, url: '@AA' },
  { name: 'Metallic microlattice', density: 0.9, url: '@AA' },
  { name: 'Molybdenum', density: 10220, url: '@AA' },
  { name: 'Neptunium', density: 20200, url: '@AA' },
  { name: 'Nickel', density: 8900, url: '@AA' },
  { name: 'Nylon', density: 1150, url: '@AA' },
  { name: 'Nimonic', density: 8100, url: '@AA' },
  { name: 'Niobium', density: 8570, url: '@AA' },
  { name: 'Oak', density: 720, url: '@AA' },
  { name: 'Osmium', density: 22570, url: '@AA' },
  { name: 'Paper', density: 700, url: '@AA' },
  { name: 'Phosphorus', density: 1820, url: '@AA' },
  { name: 'Pine', density: 350, url: '@AA' },
  { name: 'Plastics', density: 1175, url: '@AA' },
  { name: 'Platinum', density: 21450, url: '@AA' },
  { name: 'Plutonium', density: 19840, url: '@AA' },
  { name: 'Polonium', density: 9200, url: '@AA' },
  { name: 'Potassium', density: 860, url: '@AA' },
  { name: 'Promethium', density: 7260, url: '@AA' },
  { name: 'Quartz', density: 2650, url: '@AA' },
  { name: 'Radium', density: 5000, url: '@AA' },
  { name: 'Red brass', density: 8720, url: '@AA' },
  { name: 'Redwood', density: 510, url: '@AA' },
  { name: 'Rhenium', density: 21020, url: '@AA' },
  { name: 'Rhodium', density: 12410, url: '@AA' },
  { name: 'Rock salt', density: 2200, url: '@AA' },
  { name: 'Rock wool', density: 300, url: '@AA' },
  { name: 'Rubidinium', density: 1520, url: '@AA' },
  { name: 'Ruthenium', density: 12100, url: '@AA' },
  { name: 'Sand dry', density: 1500, url: '@AA' },
  { name: 'Sapphire', density: 3980, url: '@AA' },
  { name: 'Selenium', density: 4800, url: '@AA' },
  { name: 'Silicon', density: 2330, url: '@AA' },
  { name: 'Silver', density: 10500, url: '@AA' },
  { name: 'Slate', density: 2900, url: '@AA' },
  { name: 'Snow', density: 100, url: '@AA' },
  { name: 'SoapStone', density: 2900, url: '@AA' },
  { name: 'Sodium', density: 980, url: '@AA' },
  { name: 'Soy beans', density: 4, url: '@AA' },
  { name: 'Steel', density: 7820, url: '@AA' },
  { name: 'Styrofoam', density: 75, url: '@AA' },
  { name: 'Stone', density: 2600, url: '@AA' },
  { name: 'Sugar', density: 1600, url: '@AA' },
  { name: 'Tantalum', density: 16600, url: '@AA' },
  { name: 'Tetrachloroethene', density: 1622, url: '@AA' },
  { name: 'Thorium', density: 11700, url: '@AA' },
  { name: 'Tin', density: 7310, url: '@AA' },
  { name: 'Titanium', density: 4540, url: '@AA' },
  { name: 'Topaz', density: 3500, url: '@AA' },
  { name: 'Tungsten hexafluoride', density: 12.4, url: '@AA' },
  { name: 'Tungsten', density: 19300, url: '@AA' },
  { name: 'Uranium', density: 18800, url: '@AA' },
  { name: 'Vanadium', density: 6100, url: '@AA' },
  { name: 'Water(salt)', density: 1030, url: '@AA' },
  { name: 'Water', density: 1000, url: '@AA' },
  { name: 'Wood', density: 700, url: '@AA' },
  { name: 'Zebrawood', density: 790, url: '@AA' },
  { name: 'Zinc', density: 7120, url: '@AA' },
  { name: 'Zirconium', density: 6520, url: '@AA' },
];
